channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipython=8
  - pip=22.2.2
  - python=3.8.13
  - pytorch=1.9.1
  - zlib=1.2.13
  - hdf5=1.14.0
#  - cudatoolkit=11.1  # enable if GPU available
#  To work within notebooks install
#  - jupyter=1.0.0
#  - jupyterlab=3.6.3
#  - chardet=4.0.0
#  - nb_conda=2.2.1
#  - notebook<7.0.0
  - pip:
    - pytorch_lightning==1.8.1
    - tensorboard==2.11.1
    - setuptools==59.5.0  # see https://github.com/pytorch/pytorch/issues/69894
    - h5py==3.7.0
    - omegaconf==2.2.3
    - enformer-pytorch==0.5.5
    - tables==3.7.0
    - pyfaidx==0.7.1
    - pysam==0.19.0
    - pandas==1.5.3
    - scanpy==1.9.1
    - pybedtools==0.9.0
    - matplotlib==3.5.3
